FROM ubuntu
RUN apt update -y && \
    apt install -y default-jdk wget && \
    java -version && \
    apt install -y maven && \
    mvn -version

# Download Tomcat
RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.8/bin/apache-tomcat-9.0.8.tar.gz && \
    mkdir -p /opt/tomcat && \
    tar -xvzf apache-tomcat-9.0.8.tar.gz -C /opt/tomcat

# Create Tomcat user and set permissions
RUN groupadd tomcat && \
    useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat && \
    cd /opt/tomcat/apache-tomcat-9.0.8 && \
    chmod -R 755 conf bin && \
    chown -R tomcat:tomcat webapps/ work/ temp/ logs/ bin/

EXPOSE 8080
ENTRYPOINT ["/opt/tomcat/apache-tomcat-9.0.8/bin/startup.sh"]

